# Generated by Django 3.0.7 on 2021-02-18 17:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customet',
            new_name='Customer',
        ),
    ]
